// This file is generated by [oats][0] and should not be edited by hand.
//
// [0]: https://github.com/influxdata/oats

export interface Functions {
  functions?: Function[]
}

export interface Function {
  readonly id?: string
  name: string
  description?: string
  orgID: string
  script: string
  language?: FunctionLanguage
  url?: string
  readonly createdAt?: string
  readonly updatedAt?: string
}

export type FunctionLanguage = 'python' | 'flux'

export interface Error {
  readonly code:
    | 'internal error'
    | 'not found'
    | 'conflict'
    | 'invalid'
    | 'unprocessable entity'
    | 'empty value'
    | 'unavailable'
    | 'forbidden'
    | 'too many requests'
    | 'unauthorized'
    | 'method not allowed'
  readonly message: string
}

export interface FunctionCreateRequest {
  name: string
  description?: string
  orgID: string
  script: string
  language: FunctionLanguage
}

export type FunctionTriggerRequest = FunctionInvocationParams & {
  script: string
  method: 'GET' | 'POST'
  orgID?: string
  org?: string
  language: FunctionLanguage
}

export interface FunctionInvocationParams {
  params?: any
}

export type FunctionTriggerResponse = FunctionRunBase & {
  response?: FunctionHTTPResponse
}

export interface FunctionRunBase {
  readonly id?: string
  status?: 'ok' | 'error'
  error?: string
  logs?: FunctionRunLog[]
  response?: FunctionHTTPResponseNoData
  readonly startedAt?: string
}

export interface FunctionRunLog {
  message?: string
  timestamp?: string
  severity?: any
}

export interface FunctionHTTPResponseNoData {
  type?: 'http'
  dataType?: 'json'
  headers?: any
  statusCode?: '200' | '500' | '404'
}

export type FunctionHTTPResponse = FunctionHTTPResponseNoData & {
  data?: FunctionHTTPResponseData
}

export type FunctionHTTPResponseData = any

export interface FunctionUpdateRequest {
  name?: string
  description?: string
  script?: string
}

export interface FunctionRuns {
  runs?: FunctionRun[]
}

export type FunctionRun = FunctionRunBase & {
  response?: FunctionHTTPResponseNoData
}

interface RequestOptions {
  signal?: AbortSignal
}

export type RequestHandler = (
  url: string,
  query: string,
  init: RequestInit
) => {url: string; query: string; init: RequestInit}
export type ResponseHandler = (
  status: number,
  headers: Headers,
  data: any
) => {status: number; headers: Headers; data: any}

const RequestContext = function(
  requestHandler: RequestHandler,
  responseHandler: ResponseHandler
) {
  this.requestHandler = requestHandler
  this.responseHandler = responseHandler
}

RequestContext.prototype.request = async function(
  method: string,
  url: string,
  params: any = {},
  options: RequestOptions = {}
): Promise<any> {
  const requestHeaders = new Headers(params.headers)
  const contentType = requestHeaders.get('Content-Type') || ''

  if (params.auth) {
    const credentials = btoa(`${params.auth.username}:${params.auth.password}`)

    requestHeaders.append('Authorization', `Basic ${credentials}`)
  }

  const body =
    params.data && contentType.includes('json')
      ? JSON.stringify(params.data)
      : params.data

  const query = params.query ? `?${new URLSearchParams(params.query)}` : ''

  const {
    url: middlewareUrl,
    query: middlewareQuery,
    init,
  } = this.requestHandler(url, query, {
    method,
    body,
    credentials: 'same-origin',
    signal: options.signal,
    headers: requestHeaders,
  })

  const response = await fetch(`${middlewareUrl}${middlewareQuery}`, init)

  const {status, headers} = response
  const responseContentType = headers.get('Content-Type') || ''

  let data

  if (responseContentType.includes('json')) {
    data = await response.json()
  } else if (responseContentType.includes('octet-stream')) {
    data = await response.blob()
  } else if (responseContentType.includes('text')) {
    data = await response.text()
  }

  return this.responseHandler(status, headers, data)
}

RequestContext.prototype.setRequestHandler = function(
  requestHandler: RequestHandler
) {
  this.requestHandler = requestHandler
}

RequestContext.prototype.setResponseHandler = function(
  responseHandler: ResponseHandler
) {
  this.responseHandler = responseHandler
}

const rc = new RequestContext(
  (url, query, init) => {
    return {url, query, init}
  },
  (status, headers, data) => {
    return {status, headers, data}
  }
)
const request = rc.request.bind(rc)

export const setRequestHandler = rc.setRequestHandler.bind(rc)
export const setResponseHandler = rc.setResponseHandler.bind(rc)

export interface GetApiV2FunctionsParams {
  query?: {
    org?: string
    orgID?: string
    limit?: number
    offset?: number
  }
}

type GetApiV2FunctionsResult =
  | GetApiV2FunctionsOKResult
  | GetApiV2FunctionsDefaultResult

interface GetApiV2FunctionsOKResult {
  status: 200
  headers: Headers
  data: Functions
}

interface GetApiV2FunctionsDefaultResult {
  status: 500
  headers: Headers
  data: Error
}

export const getApiV2Functions = (
  params: GetApiV2FunctionsParams,
  options: RequestOptions = {}
): Promise<GetApiV2FunctionsResult> =>
  request('GET', '/api/v2/functions', params, options) as Promise<
    GetApiV2FunctionsResult
  >

export interface PostApiV2FunctionParams {
  data: FunctionCreateRequest
}

type PostApiV2FunctionResult =
  | PostApiV2FunctionCreatedResult
  | PostApiV2FunctionDefaultResult

interface PostApiV2FunctionCreatedResult {
  status: 201
  headers: Headers
  data: Function
}

interface PostApiV2FunctionDefaultResult {
  status: 500
  headers: Headers
  data: Error
}

export const postApiV2Function = (
  params: PostApiV2FunctionParams,
  options: RequestOptions = {}
): Promise<PostApiV2FunctionResult> =>
  request(
    'POST',
    '/api/v2/functions',
    {...params, headers: {'Content-Type': 'application/json'}},
    options
  ) as Promise<PostApiV2FunctionResult>

export interface PostApiV2FunctionsTriggerParams {
  data: FunctionTriggerRequest
}

type PostApiV2FunctionsTriggerResult =
  | PostApiV2FunctionsTriggerOKResult
  | PostApiV2FunctionsTriggerDefaultResult

interface PostApiV2FunctionsTriggerOKResult {
  status: 200
  headers: Headers
  data: FunctionTriggerResponse
}

interface PostApiV2FunctionsTriggerDefaultResult {
  status: 500
  headers: Headers
  data: Error
}

export const postApiV2FunctionsTrigger = (
  params: PostApiV2FunctionsTriggerParams,
  options: RequestOptions = {}
): Promise<PostApiV2FunctionsTriggerResult> =>
  request(
    'POST',
    '/api/v2/functions/trigger',
    {...params, headers: {'Content-Type': 'application/json'}},
    options
  ) as Promise<PostApiV2FunctionsTriggerResult>

export interface GetApiV2FunctionParams {
  functionID: string
}

type GetApiV2FunctionResult =
  | GetApiV2FunctionOKResult
  | GetApiV2FunctionDefaultResult

interface GetApiV2FunctionOKResult {
  status: 200
  headers: Headers
  data: Function
}

interface GetApiV2FunctionDefaultResult {
  status: 500
  headers: Headers
  data: Error
}

export const getApiV2Function = (
  params: GetApiV2FunctionParams,
  options: RequestOptions = {}
): Promise<GetApiV2FunctionResult> =>
  request(
    'GET',
    `/api/v2/functions/${params.functionID}`,
    params,
    options
  ) as Promise<GetApiV2FunctionResult>

export interface PatchApiV2FunctionParams {
  functionID: string

  data: FunctionUpdateRequest
}

type PatchApiV2FunctionResult =
  | PatchApiV2FunctionOKResult
  | PatchApiV2FunctionDefaultResult

interface PatchApiV2FunctionOKResult {
  status: 200
  headers: Headers
  data: Function
}

interface PatchApiV2FunctionDefaultResult {
  status: 500
  headers: Headers
  data: Error
}

export const patchApiV2Function = (
  params: PatchApiV2FunctionParams,
  options: RequestOptions = {}
): Promise<PatchApiV2FunctionResult> =>
  request(
    'PATCH',
    `/api/v2/functions/${params.functionID}`,
    {...params, headers: {'Content-Type': 'application/json'}},
    options
  ) as Promise<PatchApiV2FunctionResult>

export interface DeleteApiV2FunctionParams {
  functionID: string
}

type DeleteApiV2FunctionResult =
  | DeleteApiV2FunctionNoContentResult
  | DeleteApiV2FunctionDefaultResult

interface DeleteApiV2FunctionNoContentResult {
  status: 204
  headers: Headers
  data: any
}

interface DeleteApiV2FunctionDefaultResult {
  status: 500
  headers: Headers
  data: Error
}

export const deleteApiV2Function = (
  params: DeleteApiV2FunctionParams,
  options: RequestOptions = {}
): Promise<DeleteApiV2FunctionResult> =>
  request(
    'DELETE',
    `/api/v2/functions/${params.functionID}`,
    params,
    options
  ) as Promise<DeleteApiV2FunctionResult>

export interface GetApiV2FunctionsInvokeParams {
  functionID: string

  query?: {
    params?: any
  }
}

type GetApiV2FunctionsInvokeResult = GetApiV2FunctionsInvokeDefaultResult

interface GetApiV2FunctionsInvokeDefaultResult {
  status: 500
  headers: Headers
  data: FunctionHTTPResponseData
}

export const getApiV2FunctionsInvoke = (
  params: GetApiV2FunctionsInvokeParams,
  options: RequestOptions = {}
): Promise<GetApiV2FunctionsInvokeResult> =>
  request(
    'GET',
    `/api/v2/functions/${params.functionID}/invoke`,
    params,
    options
  ) as Promise<GetApiV2FunctionsInvokeResult>

export interface PostApiV2FunctionsInvokeParams {
  functionID: string

  data?: FunctionInvocationParams
}

type PostApiV2FunctionsInvokeResult = PostApiV2FunctionsInvokeDefaultResult

interface PostApiV2FunctionsInvokeDefaultResult {
  status: 500
  headers: Headers
  data: FunctionHTTPResponseData
}

export const postApiV2FunctionsInvoke = (
  params: PostApiV2FunctionsInvokeParams,
  options: RequestOptions = {}
): Promise<PostApiV2FunctionsInvokeResult> =>
  request(
    'POST',
    `/api/v2/functions/${params.functionID}/invoke`,
    {...params, headers: {'Content-Type': 'application/json'}},
    options
  ) as Promise<PostApiV2FunctionsInvokeResult>

export interface GetApiV2FunctionsRunsParams {
  functionID: string

  query?: {
    limit?: number
    offset?: number
  }
}

type GetApiV2FunctionsRunsResult =
  | GetApiV2FunctionsRunsOKResult
  | GetApiV2FunctionsRunsDefaultResult

interface GetApiV2FunctionsRunsOKResult {
  status: 200
  headers: Headers
  data: FunctionRuns
}

interface GetApiV2FunctionsRunsDefaultResult {
  status: 500
  headers: Headers
  data: Error
}

export const getApiV2FunctionsRuns = (
  params: GetApiV2FunctionsRunsParams,
  options: RequestOptions = {}
): Promise<GetApiV2FunctionsRunsResult> =>
  request(
    'GET',
    `/api/v2/functions/${params.functionID}/runs`,
    params,
    options
  ) as Promise<GetApiV2FunctionsRunsResult>

export interface GetApiV2FunctionsRunParams {
  functionID: string
  runID: string
}

type GetApiV2FunctionsRunResult =
  | GetApiV2FunctionsRunOKResult
  | GetApiV2FunctionsRunDefaultResult

interface GetApiV2FunctionsRunOKResult {
  status: 200
  headers: Headers
  data: FunctionRun
}

interface GetApiV2FunctionsRunDefaultResult {
  status: 500
  headers: Headers
  data: Error
}

export const getApiV2FunctionsRun = (
  params: GetApiV2FunctionsRunParams,
  options: RequestOptions = {}
): Promise<GetApiV2FunctionsRunResult> =>
  request(
    'GET',
    `/api/v2/functions/${params.functionID}/runs/${params.runID}`,
    params,
    options
  ) as Promise<GetApiV2FunctionsRunResult>
